
/* Drop Tables */

DROP TABLE CONTENTS_PICTURE CASCADE CONSTRAINTS;
DROP TABLE RECOMMEND CASCADE CONSTRAINTS;
DROP TABLE REPLY CASCADE CONSTRAINTS;
DROP TABLE BOARD CASCADE CONSTRAINTS;
DROP TABLE MEMBER_INFO CASCADE CONSTRAINTS;




/* Create Tables */

-- 게시판
CREATE TABLE BOARD
(
	-- 게시물번호
	B_NO number(6) NOT NULL,
	-- 아이디
	M_ID varchar2(10) NOT NULL,
	-- 무드
	B_MOOD char(1) NOT NULL,
	-- 글제목
	B_TITLE varchar2(60) NOT NULL,
	-- 글내용
	B_CONTENT varchar2(3000) NOT NULL,
	-- 작성일
	B_REG_DATE varchar2(14) NOT NULL,
	-- 수정일
	B_UPDATE_DATE varchar2(14) NOT NULL,
	-- 추천
	B_LIKE number(5,0) NOT NULL,
	-- 게시글타입
	B_TYPE char(1) NOT NULL,
	PRIMARY KEY (B_NO)
);


-- 첨부파일
CREATE TABLE CONTENTS_PICTURE
(
	-- 파일아이디
	UUID varchar2(10) NOT NULL,
	-- 게시물번호
	B_NO number(6) NOT NULL,
	-- 파일경로
	F_PATH varchar2(255) NOT NULL,
	-- 파일이름
	F_NAME varchar2(100) NOT NULL,
	-- 파일형식
	F_TYPE char(1) NOT NULL,
	PRIMARY KEY (UUID)
);


-- 필수회원정보
CREATE TABLE MEMBER_INFO
(
	-- 아이디
	M_ID varchar2(10) NOT NULL,
	-- 비밀번호
	M_PASSWORD varchar2(20) NOT NULL,
	-- 닉네임
	M_NICK varchar2(30) NOT NULL UNIQUE,
	-- 이메일
	M_EMAIL varchar2(30),
	-- 가입일
	M_REG_DATE varchar2(14) NOT NULL,
	-- 회원권한
	M_GRADE char(1) NOT NULL,
	PRIMARY KEY (M_ID)
);


-- 추천
CREATE TABLE RECOMMEND
(
	-- 추천번호
	RE_NUM number(7) NOT NULL,
	-- 게시물번호
	B_NO number(6) NOT NULL,
	-- 아이디
	M_ID varchar2(10) NOT NULL UNIQUE,
	PRIMARY KEY (RE_NUM)
);


-- 댓글
CREATE TABLE REPLY
(
	-- 댓글번호
	R_NO number(7) NOT NULL,
	-- 게시물번호
	B_NO number(6) NOT NULL,
	-- 아이디
	M_ID varchar2(10) NOT NULL,
	-- 댓글내용
	R_CONTENTS varchar2(1000) NOT NULL,
	-- 댓글작성일
	R_REG_DATE varchar2(14) NOT NULL,
	-- 댓글수정일
	R_UPDATE_DATE varchar2(14) NOT NULL,
	PRIMARY KEY (R_NO)
);



/* Create Foreign Keys */

ALTER TABLE CONTENTS_PICTURE
	ADD FOREIGN KEY (B_NO)
	REFERENCES BOARD (B_NO)
;


ALTER TABLE RECOMMEND
	ADD FOREIGN KEY (B_NO)
	REFERENCES BOARD (B_NO)
;


ALTER TABLE REPLY
	ADD FOREIGN KEY (B_NO)
	REFERENCES BOARD (B_NO)
;


ALTER TABLE BOARD
	ADD FOREIGN KEY (M_ID)
	REFERENCES MEMBER_INFO (M_ID)
;


ALTER TABLE RECOMMEND
	ADD FOREIGN KEY (M_ID)
	REFERENCES MEMBER_INFO (M_ID)
;


ALTER TABLE REPLY
	ADD FOREIGN KEY (M_ID)
	REFERENCES MEMBER_INFO (M_ID)
;



/* Comments */

COMMENT ON TABLE BOARD IS '게시판';
COMMENT ON COLUMN BOARD.B_NO IS '게시물번호';
COMMENT ON COLUMN BOARD.M_ID IS '아이디';
COMMENT ON COLUMN BOARD.B_MOOD IS '무드';
COMMENT ON COLUMN BOARD.B_TITLE IS '글제목';
COMMENT ON COLUMN BOARD.B_CONTENT IS '글내용';
COMMENT ON COLUMN BOARD.B_REG_DATE IS '작성일';
COMMENT ON COLUMN BOARD.B_UPDATE_DATE IS '수정일';
COMMENT ON COLUMN BOARD.B_LIKE IS '추천';
COMMENT ON COLUMN BOARD.B_TYPE IS '게시글타입';
COMMENT ON TABLE CONTENTS_PICTURE IS '첨부파일';
COMMENT ON COLUMN CONTENTS_PICTURE.UUID IS '파일아이디';
COMMENT ON COLUMN CONTENTS_PICTURE.B_NO IS '게시물번호';
COMMENT ON COLUMN CONTENTS_PICTURE.F_PATH IS '파일경로';
COMMENT ON COLUMN CONTENTS_PICTURE.F_NAME IS '파일이름';
COMMENT ON COLUMN CONTENTS_PICTURE.F_TYPE IS '파일형식';
COMMENT ON TABLE MEMBER_INFO IS '필수회원정보';
COMMENT ON COLUMN MEMBER_INFO.M_ID IS '아이디';
COMMENT ON COLUMN MEMBER_INFO.M_PASSWORD IS '비밀번호';
COMMENT ON COLUMN MEMBER_INFO.M_NICK IS '닉네임';
COMMENT ON COLUMN MEMBER_INFO.M_EMAIL IS '이메일';
COMMENT ON COLUMN MEMBER_INFO.M_REG_DATE IS '가입일';
COMMENT ON COLUMN MEMBER_INFO.M_GRADE IS '회원권한';
COMMENT ON TABLE RECOMMEND IS '추천';
COMMENT ON COLUMN RECOMMEND.RE_NUM IS '추천번호';
COMMENT ON COLUMN RECOMMEND.B_NO IS '게시물번호';
COMMENT ON COLUMN RECOMMEND.M_ID IS '아이디';
COMMENT ON TABLE REPLY IS '댓글';
COMMENT ON COLUMN REPLY.R_NO IS '댓글번호';
COMMENT ON COLUMN REPLY.B_NO IS '게시물번호';
COMMENT ON COLUMN REPLY.M_ID IS '아이디';
COMMENT ON COLUMN REPLY.R_CONTENTS IS '댓글내용';
COMMENT ON COLUMN REPLY.R_REG_DATE IS '댓글작성일';
COMMENT ON COLUMN REPLY.R_UPDATE_DATE IS '댓글수정일';



